In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"name":['kim','lee','park'], "age":[25,31,28],"score":[88,92,79]})

In [3]:
df  #판다스 2차원 데이터구조인 데이터프레임(표)의 형태로 출력된 것, 데이터전처리 등에 쓰임 판다스는

   name  age  score
0   kim   25     88
1   lee   31     92
2  park   28     79

In [4]:
df.to_csv('soore.csv')  #이렇게 하면 클라우드에 저장됨, 로컬컴퓨터(본인거)에 저장하려면 다르게 해야됨
#본인컴에 저장되게 코랩에서 쓰려면 코랩에 파일을 먼저 업로드해야됨-데이터파일은 케글에서 가져오면 좋음
#코랩에 일일히 드래그인 드롭 안하려면 구글드라이브 마운트해서 쓰면 더 편리하긴함
#from google.colab import drive
#drive.mount('/content/drive')

In [7]:
#업로드한 파일 여는법
iris_df = pd.read_csv('Iris.csv')  #파일명 대소문자 구분해서 정확히 써야열림

In [8]:
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [11]:
iris_df.shape
iris_df.columns  #칼럼은 테이블이자 행/행 개수
iris_df.index    #인덱스는 열/열 개
iris_df.dtypes   #각 컬럼이 어떤 데이터 타입인지 알 수 있음
iris_df.head()   #상위 n행 보기
#iris_df.tall(n)   하위 n행 보기
iris_df.info()   #데이터프레임에 대한 총정리 자료(칼럼-인덱스 수, 칼럼명, 빈칸 수(nun-null), 칸에 드간 내용의 타입(dtype) 등)
iris_df.describe()  #통계수치들 알려줌(평균, 표준편차, 최대값, 최소값, 4분위값(100-75-50-25))
#데이터 넣고 나면 info로 확인 반드시 해봐야함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [14]:
iris_df[['SepalLengthCm','Species']]

     SepalLengthCm         Species
0              5.1     Iris-setosa
1              4.9     Iris-setosa
2              4.7     Iris-setosa
3              4.6     Iris-setosa
4              5.0     Iris-setosa
..             ...             ...
145            6.7  Iris-virginica
146            6.3  Iris-virginica
147            6.5  Iris-virginica
148            6.2  Iris-virginica
149            5.9  Iris-virginica

[150 rows x 2 columns]

In [18]:
iris_df.loc[iris_df['Species']==input('종을 입력해주세요'),'Id':'Species']

종을 입력해주세요Iris-setosa

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

판다스는 이까지 하고 심화문법 / 중간준비하면서 다써본건데 이제 배우네..

In [21]:
s = "apple,banana,orange"
print(s.split(","))  #"" 사이에 드가는건 자르는 기준선 ""하면 공백 기준으로 자름
words = ["hello", "world", "python"]
print(" ".join(words)) #"" 사이에 드가는 넣어서 갖다합치기, 공백 별도 첨가임 ""하면 공백X

['apple', 'banana', 'orange']
helloworldpython

In [23]:
#리스트 컴프리헨션: 반복이나 조건문 넣어서 리스트 값을 짧게 쭉 이어쓰게 해주는건데 간결하긴하나 풀어써도 되는걸 묶어서 쓰니 적는게 복잡해져서 딱히 장점이 없
nums = [1, 2, 3, 4, 5]
print([n*n for n in nums])
res = []
res += ["even"] if 4 % 2 == 0 else ["odd"]
print(res)

[1, 4, 9, 16, 25]
['even']

In [24]:
double = lambda x: x * 2  #임의함수 일괄적용
print(double(5))

str_nums = ["1", "2", "3", "10"]  #그냥 map을 이용한 일괄적용
nums = list(map(int, str_nums))
print(nums)

10
[1, 2, 3, 10]

In [25]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9]

odds = list(filter(lambda x: x % 2 == 1, nums))   #필터로 거르는건데 람다 넣어서 일괄 적용해 걸러냄
print(odds)

[1, 3, 5, 7, 9]